import { Button } from "@/components/ui/button";
import Navbar from "./dashboard/_components/navbar";
import { SignedIn, SignedOut } from "@clerk/nextjs";
import Link from "next/link";

export default function Home() {
  return (
    <div className="bg-gradient-to-b from-gray-50 to-white">
      <Navbar />
      <div className="min-h-screen">
        {/* Hero Section */}
        <section className="relative overflow-hidden py-32 mt-10">
          <div className="absolute inset-0 bg-gradient-to-r from-indigo-600 to-purple-600 opacity-90" />
          {/* Decorative elements */}
          <div className="absolute inset-0 opacity-20">
            <div className="absolute top-20 left-0 w-72 h-72 bg-purple-500 rounded-full mix-blend-multiply filter blur-xl" />
            <div className="absolute top-40 right-0 w-72 h-72 bg-indigo-500 rounded-full mix-blend-multiply filter blur-xl" />
          </div>

          <div className="relative container mx-auto px-4 text-center">
            <h1 className="text-5xl md:text-7xl font-bold mb-8 text-white tracking-tight">
              Perfect Your
              <span className="bg-clip-text text-transparent bg-gradient-to-r from-pink-200 to-purple-200 ml-4">
                Interview Skills
              </span>
            </h1>
            <p className="text-xl md:text-2xl mb-12 text-gray-100 max-w-2xl mx-auto leading-relaxed">
              Master the art of interviewing with our AI-powered platform
              designed for your success.
            </p>
            <SignedIn>
              <Link href="/dashboard">
                <Button className="px-10 py-6 text-lg bg-white text-indigo-600 hover:bg-gray-100 transition-all duration-200 shadow-lg hover:shadow-xl rounded-xl">
                  Launch Dashboard
                </Button>
              </Link>
            </SignedIn>
            <SignedOut>
              <Link href="/sign-in">
                <Button className="px-10 py-6 text-lg bg-white text-indigo-600 hover:bg-gray-100 transition-all duration-200 shadow-lg hover:shadow-xl rounded-xl">
                  Get Started
                </Button>
              </Link>
            </SignedOut>
          </div>
        </section>

        {/* Features Section */}
        <section className="py-24 bg-white">
          <div className="container mx-auto px-4 text-center">
            <h2 className="text-4xl font-bold mb-16 text-gray-800">
              Powerful Features
            </h2>
            <div className="grid md:grid-cols-3 gap-10">
              <div className="p-8 bg-white rounded-2xl shadow-lg hover:shadow-xl transition-shadow duration-300 border border-gray-100">
                <div className="w-16 h-16 bg-indigo-100 rounded-2xl flex items-center justify-center mx-auto mb-6">
                  <svg
                    className="w-8 h-8 text-indigo-600"
                    fill="none"
                    stroke="currentColor"
                    viewBox="0 0 24 24">
                    <path
                      strokeLinecap="round"
                      strokeLinejoin="round"
                      strokeWidth="2"
                      d="M8 12h.01M12 12h.01M16 12h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z"
                    />
                  </svg>
                </div>
                <h3 className="text-2xl font-bold mb-4 text-gray-800">
                  AI Question Generation
                </h3>
                <p className="text-gray-600 leading-relaxed">
                  Get personalized interview questions generated by our advanced
                  AI system.
                </p>
              </div>
              <div className="p-8 bg-white rounded-2xl shadow-lg hover:shadow-xl transition-shadow duration-300 border border-gray-100">
                <div className="w-16 h-16 bg-purple-100 rounded-2xl flex items-center justify-center mx-auto mb-6">
                  <svg
                    className="w-8 h-8 text-purple-600"
                    fill="none"
                    stroke="currentColor"
                    viewBox="0 0 24 24">
                    <path
                      strokeLinecap="round"
                      strokeLinejoin="round"
                      strokeWidth="2"
                      d="M15 10l4.553-2.276A1 1 0 0121 8.618v6.764a1 1 0 01-1.447.894L15 14M5 18h8a2 2 0 002-2V8a2 2 0 00-2-2H5a2 2 0 00-2 2v8a2 2 0 002 2z"
                    />
                  </svg>
                </div>
                <h3 className="text-2xl font-bold mb-4 text-gray-800">
                  Answer Recording
                </h3>
                <p className="text-gray-600 leading-relaxed">
                  Record your responses and receive comprehensive feedback for
                  improvement.
                </p>
              </div>
              <div className="p-8 bg-white rounded-2xl shadow-lg hover:shadow-xl transition-shadow duration-300 border border-gray-100">
                <div className="w-16 h-16 bg-pink-100 rounded-2xl flex items-center justify-center mx-auto mb-6">
                  <svg
                    className="w-8 h-8 text-pink-600"
                    fill="none"
                    stroke="currentColor"
                    viewBox="0 0 24 24">
                    <path
                      strokeLinecap="round"
                      strokeLinejoin="round"
                      strokeWidth="2"
                      d="M9 5H7a2 2 0 00-2 2v12a2 2 0 002 2h10a2 2 0 002-2V7a2 2 0 00-2-2h-2M9 5a2 2 0 002 2h2a2 2 0 002-2M9 5a2 2 0 012-2h2a2 2 0 012 2"
                    />
                  </svg>
                </div>
                <h3 className="text-2xl font-bold mb-4 text-gray-800">
                  Detailed Feedback
                </h3>
                <p className="text-gray-600 leading-relaxed">
                  Get structured feedback with actionable insights to enhance
                  your interview performance.
                </p>
              </div>
            </div>
          </div>
        </section>

        {/* Testimonials Section */}
        <section className="py-24 bg-gray-50">
          <div className="container mx-auto px-4 text-center">
            <h2 className="text-4xl font-bold mb-16 text-gray-800">
              Success Stories
            </h2>
            <div className="grid md:grid-cols-2 gap-10 max-w-4xl mx-auto">
              <div className="p-8 bg-white rounded-2xl shadow-lg hover:shadow-xl transition-shadow duration-300">
                <p className="text-gray-600 mb-6 text-lg leading-relaxed">
                  "This platform transformed my interview preparation. The AI
                  feedback was spot-on and helped me secure my dream job!"
                </p>
                <div className="flex items-center justify-center">
                  <div className="w-12 h-12 bg-gray-200 rounded-full mr-4"></div>
                  <div className="text-left">
                    <p className="font-bold text-gray-800">Sarah Johnson</p>
                    <p className="text-gray-600">Software Engineer</p>
                  </div>
                </div>
              </div>
              <div className="p-8 bg-white rounded-2xl shadow-lg hover:shadow-xl transition-shadow duration-300">
                <p className="text-gray-600 mb-6 text-lg leading-relaxed">
                  "The structured feedback and practice sessions gave me the
                  confidence I needed. Highly recommended!"
                </p>
                <div className="flex items-center justify-center">
                  <div className="w-12 h-12 bg-gray-200 rounded-full mr-4"></div>
                  <div className="text-left">
                    <p className="font-bold text-gray-800">Michael Chen</p>
                    <p className="text-gray-600">Product Manager</p>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </section>

        {/* CTA Section */}
        <section className="relative overflow-hidden py-24">
          <div className="absolute inset-0 bg-gradient-to-r from-purple-600 to-indigo-600 opacity-90" />
          <div className="absolute inset-0 opacity-20">
            <div className="absolute bottom-0 left-0 w-72 h-72 bg-purple-500 rounded-full mix-blend-multiply filter blur-xl" />
            <div className="absolute top-0 right-0 w-72 h-72 bg-indigo-500 rounded-full mix-blend-multiply filter blur-xl" />
          </div>

          <div className="relative container mx-auto px-4 text-center">
            <h2 className="text-4xl md:text-5xl font-bold mb-8 text-white tracking-tight">
              Ready to Transform Your Interview Skills?
            </h2>
            <p className="text-xl text-gray-100 mb-12 max-w-2xl mx-auto">
              Join thousands of successful candidates who have mastered their
              interviews with our platform.
            </p>
            <SignedIn>
              <Link href="/dashboard">
                <Button className="px-10 py-6 text-lg bg-white text-indigo-600 hover:bg-gray-100 transition-all duration-200 shadow-lg hover:shadow-xl rounded-xl">
                  Start Now
                </Button>
              </Link>
            </SignedIn>
            <SignedOut>
              <Link href="/sign-in">
                <Button className="px-10 py-6 text-lg bg-white text-indigo-600 hover:bg-gray-100 transition-all duration-200 shadow-lg hover:shadow-xl rounded-xl">
                  Begin Your Journey
                </Button>
              </Link>
            </SignedOut>
          </div>
        </section>
      </div>
    </div>
  );
}
